server:
  port: 8001

spring:
  application:
    name: auth-service
  mail:
    host: smtp.163.com
    username: zzzyt217@163.com
    password: THULqamnbVa3RWL4


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


